# Generated by Django 3.1.2 on 2021-03-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0003_auto_20210320_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_approved', models.BooleanField(default=False)),
                ('in_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.member')),
                ('in_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.slot')),
            ],
        ),
    ]
