# Generated by Django 3.1.7 on 2021-03-19 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('comp_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mysite.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='age')),
                ('gender', models.CharField(max_length=10, verbose_name='gender')),
                ('game_type', models.CharField(max_length=100, verbose_name='type')),
                ('comp_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compPage.competition')),
            ],
        ),
    ]
