# Generated by Django 3.1.2 on 2021-03-20 18:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210319_0526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='comp_slot',
        ),
        migrations.AddField(
            model_name='competition',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='in_slot',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.slot'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tickets', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='num_tickets')),
                ('in_competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compPage.competition')),
                ('in_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
