# Generated by Django 3.1.7 on 2021-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210321_1807'),
        ('suggestionPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='complaint',
            name='coordinator',
            field=models.ManyToManyField(to='mysite.Coordinator'),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='member',
        ),
        migrations.AddField(
            model_name='feedback',
            name='member',
            field=models.ManyToManyField(to='mysite.Member'),
        ),
    ]
