# Generated by Django 3.1.7 on 2021-03-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursePage', '0001_initial'),
        ('partyPage', '0001_initial'),
        ('compPage', '0002_auto_20210321_1743'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursePage.course'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partyPage.event'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compPage.competition'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursePage.course'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partyPage.event'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='game',
            field=models.ManyToManyField(blank=True, to='compPage.Game'),
        ),
    ]
